trigger:
  branches:
    include:
      - main
 
pool:
  name: 'pool'
 
variables:
  buildConfiguration: 'Release'
  dotnetVersion: '8.x'
 
stages:
 
  - stage: Build
    displayName: 'Build & Test'
    jobs:
      - job: BuildJob
        displayName: 'Build, Test, Publish'
        steps:
 
          # 1. Set up .NET
          - task: UseDotNet@2
            displayName: 'Set up .NET 8'
            inputs:
              version: '$(dotnetVersion)'
 
          # 2. Restore NuGet packages
          - task: DotNetCoreCLI@2
            displayName: 'Restore NuGet packages'
            inputs:
              command: 'restore'
              projects: '**/*.csproj'
 
          # 3. Build the solution
          - task: DotNetCoreCLI@2
            displayName: 'Build solution'
            inputs:
              command: 'build'
              projects: '**/*.csproj'
              arguments: '--configuration $(buildConfiguration) --no-restore'
 
 
          # 4. Publish the app
          - task: DotNetCoreCLI@2
            displayName: 'Publish app'
            inputs:
              command: 'publish'
              publishWebProjects: true
              arguments: >-
                --configuration $(buildConfiguration)
                --output $(Build.ArtifactStagingDirectory)
                --no-build
              zipAfterPublish: true
 
          # 5. Upload artifact
          - task: PublishBuildArtifacts@1
            displayName: 'Upload artifact'
            inputs:
              pathToPublish: '$(Build.ArtifactStagingDirectory)'
              artifactName: 'WebApplicationDDD'